### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by ndelvalle** [Huemul/trae#169]
Required changes to V2:

* Remove multiple builds
* Fix multipart form data upload (#69)
* Enhance implementation and API

Personal proposals:

* Remove `trae.defaults()` method (Not passing any arguments), In my opinion, this is kind of confusing. We can create something like `getConfig`, or maybe expose a `config` attribute.
* Remove `trae.baseUrl([url])` method. We can achieve the same functionality using defaults or defining it when we create a new instance. 
* Make `trae.finally([middleware])` async. After all promises finally are async.
* Use `statusCode` instead of `status` on response objects
* Remove `all-contributors` implementation. We don't have time to update this and contributors are already shown by github
* Remove the `request` method. I'm not entarely convinced yet, but I don't like it much
* Add a timeout functionality

Branch: [v2](https://github.com/Huemul/trae/tree/v2)

**Comment by gillchristian** [comment]
For "Enhance implementation and API" I suggests:

- Make methods static instead of creating them as class properties.
- Only keep public methods as part of the `Trae` class. Internal methods could be functions instead.

Agree with most of the "Personal proposals". Only question about two items:

- Make `trae.finally([middleware])` async: I wonder how much `finally` is used. Instead of making it `async` I would make it so accepts one function and that's the only thing it runs. If then someone wants to add multiple functions to it they can `compose` or `composeP` those functions. And now that I mention this maybe it also makes sense for the other middleware. Wdyt? 
- Add a timeout functionality: what do you propose? I wouldn't delay `v2` for this one. Would rather have it as `v2.x`. I also wanted to add TypeScript support but better leave it for `v2.x`.

**Comment by gillchristian** [comment]
For "Enhance implementation and API" I suggests:

- Make methods static instead of creating them as class properties.
- Only keep public methods as part of the `Trae` class. Internal methods could be functions instead.

Agree with most of the "Personal proposals". Only question about two items:

- Make `trae.finally([middleware])` async: I wonder how much `finally` is used. Instead of making it `async` I would make it so accepts one function and that's the only thing it runs. If then someone wants to add multiple functions to it they can `compose` or `composeP` those functions. And now that I mention this maybe it also makes sense for the other middleware. Wdyt? 
- Add a timeout functionality: what do you propose? I wouldn't delay `v2` for this one. Would rather have it as `v2.x`. I also wanted to add TypeScript support but better leave it for `v2.x`.

**Comment by gillchristian** [comment]
For "Enhance implementation and API" I suggests:

- Make methods static instead of creating them as class properties.
- Only keep public methods as part of the `Trae` class. Internal methods could be functions instead.

Agree with most of the "Personal proposals". Only question about two items:

- Make `trae.finally([middleware])` async: I wonder how much `finally` is used. Instead of making it `async` I would make it so accepts one function and that's the only thing it runs. If then someone wants to add multiple functions to it they can `compose` or `composeP` those functions. And now that I mention this maybe it also makes sense for the other middleware. Wdyt? 
- Add a timeout functionality: what do you propose? I wouldn't delay `v2` for this one. Would rather have it as `v2.x`. I also wanted to add TypeScript support but better leave it for `v2.x`.

**Comment by gillchristian** [comment]
For "Enhance implementation and API" I suggests:

- Make methods static instead of creating them as class properties.
- Only keep public methods as part of the `Trae` class. Internal methods could be functions instead.

Agree with most of the "Personal proposals". Only question about two items:

- Make `trae.finally([middleware])` async: I wonder how much `finally` is used. Instead of making it `async` I would make it so accepts one function and that's the only thing it runs. If then someone wants to add multiple functions to it they can `compose` or `composeP` those functions. And now that I mention this maybe it also makes sense for the other middleware. Wdyt? 
- Add a timeout functionality: what do you propose? I wouldn't delay `v2` for this one. Would rather have it as `v2.x`. I also wanted to add TypeScript support but better leave it for `v2.x`.

**Comment by ndelvalle** [comment]
@gillchristian 
I agree with your Enhance suggestions. About your questions:
* I think it makes sense to have just one `finally`, otherwise it can be a bit confusing. I'd like to kind of replicate promises approach
* Definitely, I agree with you here.

👍

**Comment by gillchristian** [comment]
I'll close this and create a new one
