### ISSUE TITLE
Default Headers

### ISSUE THREAD

**Issue by fredguest** [Huemul/trae#43]
Really nice library, thanks for building and OSing it!

I just wanted to understand the thinking behind setting `'Accept'` and `'Content-Type'` by default, because the mere presence of `'Content-Type'` triggers a CORS preflight that would not otherwise occur, and in my case I was getting the following error as a result `Fetch API cannot load https://foo.com. Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.` I was able to fix the issue with the following code:

```js
const api = trae.create({ baseUrl: 'https://foo.com/api/v1' });

api.before((config) => {
  delete config.headers;
  return config;
});

export { api };
```

...but it seems a little clunky to need to use middleware, and to mutate the config object to remove a key that I'd rather not have present in the first place. Is there a less clunky way to remove the default headers, and is it worth revisiting the decision to include them?

**Comment by gillchristian** [comment]
Hi Fred, thanks! And thanks for the feedback, as you see this is been out just yet, so a lot of issues like this one will come out when other people use it.

It makes sense to remove the defaults, I guess they are there because it were the ones we were using the most when we wrote it.

We are discussing a shorthand to add & remove headers and also a way to have specific headers for each method.

Any further suggestions you might have will be helpful :smile:

**Comment by fredguest** [comment]
Good call, that's a little bit better 👌🏼. The empty object doesn't seem to cause any preflight issues. Ya ultimately I think it's probably cleanest not to have default headers and just let the end user be explicit. I do like the idea of being able to set different default headers per method, that sounds useful for sure. I'm happy to make a pull request to remove the default headers if you like, but if you're planning other related changes maybe you'd like to handle it yourself. Let me know!

**Comment by ndelvalle** [comment]
In my opinion most users will use these headers. So if we change this, most user will have to add them manually. I like the idea of having something ready to use with no much configuration, but at the same time I agree with you, setting defaults just because we think you are going to use them, is not that cool. So I think we should remove those defaults. I'll  appriciate if you make the mentioned PR 🙂.

We should come up with an easy way to impelement most used headers for users that want no configuration, I'm thinking of importing the lib and posting a json with the correct content type.

**Comment by ianaya89** [comment]
I am agree with both of you. I think that most people will use defaults but other people not. What do you think about adding an extra parameter (`boolean`) to indicate whenever turn off or turn on defaults in each `request`?

Even it could be part of the `config` object:

```javascript
  trae.get({ url: '/user', defaults: false });
```

**Comment by gillchristian** [comment]
That would be an option. I would just change the name because `trae.defaults()` is used to set the config so it could imply that you are disabling everything, and not just the headers.

We do need to differentiate headers for methods that have a body (`'PATCH`, `'PUT'`, `'POST'`) from those that do not have it (`'GET'`, `'HEAD'`, `'DELETE'`). Because of the `'Content-type'` header and [this](http://stackoverflow.com/a/16693884). I assume that's what was causing the preflight issue to @fredguest.
One quick solution for this is to have separated instances for the different methods but I think we can do better than that.

So we have to things to solve here:

- Differentiate headers by request method, and also have common ones.
- An easy way to set/unset headers (or any config).

**Comment by fredguest** [comment]
Just as a sanity check, looking around at other libs like Axios, they do not set any type of headers by default, you simply set them per instance https://github.com/mzabriskie/axios#creating-an-instance I think this is probably the right approach just because the requirements for headers are too varied to safely make assumptions about. In terms of being able to set default headers per method, I think the ideal API would be that something like this sets the default baseUrl and headers for all methods:

```js
const api = trae.create({
  baseUrl: 'https://foo.com/api/v1',
  headers: {
    'Accept': 'foo',
    'Content-Type': 'bar'
  }
})
```

and something like this would set the baseUrl for all methods and the headers for only the specific methods declared:

```js
const api = trae.create({
  baseUrl: 'https://foo.com/api/v1',
  getConfigs: {
    headers: {
      'Accept': 'foo',
      'Content-Type': 'bar'
    }
  },
  postConfigs: {
    headers: {
      'Accept': 'lol',
      'Content-Type': 'wut'
    }
  },
})
```

...and actually the per methods configs don't need to be limited to headers, you could allow any config to be method specific.

**Comment by gillchristian** [comment]
I agree with @fredguest here. Setting the headers for you should not be a responsibility of the library.

Anyways actually [axios](https://github.com/mzabriskie/axios/blob/master/lib/defaults.js#L6) [does](https://github.com/mzabriskie/axios/blob/master/lib/defaults.js#L88) set defaults, just for the methods with body though.

I like Fred's approach, I'd just use the method name as key so it can be easily consumed (_internally_) when doing the request.

As I corrected myself  `"An easy way to set/unset headers (or any config)."` is already there. We could provide some middlewares to set the most common headers like:

```js
import { contentTypeJson } from "trae/middlewares"

trae.before(setContentTypeJson)
```

**Comment by gillchristian** [comment]
Closing this in favor of #47
