### ISSUE TITLE
How to get response object in reject middleware?

### ISSUE THREAD

**Issue by schovi** [Huemul/trae#59]
Our server returns statuses like 400 with some json explaining what happens. Is there any way, how to get response object in rejectMiddleware to get these data and respond to them globally?

```
trae.after(null, (err) => {
  // Give me the response here :(
});
```

**Comment by gillchristian** [comment]
That makes sense, we totally missed it :confused:

I guess we could do something similar to what we are doing with the success:

```js
trae.after(null, (err) => {
  err.data // response data will be here
});
```

What do you think @ndelvalle @ianaya89 ?

**Comment by schovi** [comment]
@gillchristian Can there be whole response? `err.response` ?

**Comment by ndelvalle** [comment]
@schovi, We are currently attaching the response `status`, `statusText` and `headers` in case that is not enough I think it makes sense to do something like you are suggesting.

I'm not sure if merge the `response` object with the `error` (Not just adding the data like @gillchristian  suggested). Or add a response attribute to the `error` object 🤔.

**Comment by ndelvalle** [comment]
I think is a bit cleaner to have a `response` attribute in the `error` but I don't like having duplicate, like the `status` etc...

**Comment by gillchristian** [comment]
I don't see any use of getting the response and also the status, statusText headers, and data, that's pretty much the response. And you would have to read the data from the response, which is kind of the motivation behind having `trae` do it for you.

What use do you see for having the raw response instead of getting it already processed @schovi?

**Comment by schovi** [comment]
@gillchristian i think having raw response is more consistent. You can pass it thru same workflow as when request is successful

**Comment by gillchristian** [comment]
We are not passing the raw response either in the success case. That's actually why I suggested returning the data.

Maybe for consistency instead of returning an error object with the `status`, `statusText` & `headers` properties, we could return a regular object with an error field, alongside the other fields. But actually, on the rejection, it is expected to get an error.

One thing that comes to my mind here is to have a more controlled way to decide when a response is rejected. By `fetch` standards it only throws (and goes to `catch`) when there was an actual error on the request (time out, no internet connection, etc.). This is [explained better here ](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) (look for the _Checking that the fetch was successful_ subtitle).

So we could do something like what [`axios` does](https://github.com/mzabriskie/axios#request-config). Accept a function to customize that behavior:

```js
  // `validateStatus` defines whether to resolve or reject the promise for a given
  // HTTP response status code. If `validateStatus` returns `true` (or is set to `null`
  // or `undefined`), the promise will be resolved; otherwise, the promise will be
  // rejected.
  validateStatus: function (status) {
    return status >= 200 && status < 300; // default
  },
```
_That's copied from the Axios readme._

**Comment by schovi** [comment]
@gillchristian Sorry. By "raw response" I mean same as for success ofc :)

For me it makes sense to add response to Error object. It feels natural to me and it is something what I always look for when using some library.

Other features like customizing valid status sounds great too. It can give you more precise controling, but on other hand I am not sure, how much complex and customizable should trae be. I would recommend to discuss it separately in other issue.

**Comment by gillchristian** [comment]
That makes sense! Then I'll add the data field like in the success. I think I will have some time over the weekend, can't do it earlier than that.

If you'd like to contribute and have the time to do it before that'd be great!

**Comment by gillchristian** [comment]
Closing since #60 was merged.
